### ISSUE TITLE
mcServer.stop() Fails

### ISSUE THREAD

**Issue by KaidenP** [Egoscio/gelato#5]
```
TypeError: Cannot read property 'kill' of undefined
    at Timeout.stop [as _onTimeout] (./gelato/lib/minecraft.js:61:36)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by KaidenP** [comment]
I now realise that this was my mistake, however, It Still won't kill the child.

**Comment by KaidenP** [comment]
Considering the below js, server fails to be killed:

```
const gelato = require('../index.js')
const startPath = './start.sh'
const mcServer = new gelato.minecraft.Server(startPath) // Change this according to your setup.

mcServer.start()
mcServer.on('data', (data) => {
  console.log(data)
})

setTimeout(function(){
    mcServer.stop()
},10000)
```

**Comment by Egoscio-zz** [comment]
I tried both the .stop() and .write() methods and they aren't working. I will begin investigating shortly.

**Comment by Egoscio-zz** [comment]
Fixed .write() function in https://github.com/Egoscio/gelato/commit/a8202cefaeaa22ead371113742cc1d7e27e26733

When you invoke the .stop() method, are you still able to join the server? I .stop()'d and was no longer able to write to the console, assuming it actually shut down.

**Comment by Egoscio-zz** [comment]
Here is a demonstration of the `.stop()` function actually working:

First I added this to example/index.js to enable REPL capability:

```js
const replSrv = require('repl').start({ useGlobal: false })
replSrv.context.mcServer = mcServer
```

Next, I demonstrate the write function before and after stopping the server:

```
[23:09:42] [Server thread/INFO]: Done (3.722s)! For help, type "help" or "?"
> mcServer.write('say Hello, world.')
undefined
> [23:11:11] [Server thread/INFO]: [Server] Hello, world.
mcServer.stop()
undefined
> mcServer.write('say Am I still working?')
TypeError: Cannot read property 'write' of undefined
    at Server.write (/Users/egoscio/Github/gelato/lib/minecraft.js:54:42)
    at repl:1:10
    at ContextifyScript.Script.runInContext (vm.js:37:29)
    at REPLServer.defaultEval (repl.js:315:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:513:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:247:10)
```

**Comment by kkprince1998** [comment]
I'm on mobile and currently unable to test, but perhaps it would be easier to `write("\x03")` which is the Ctrl-C code to stop it?

**Comment by KaidenP** [comment]
For some reason, stop still does not work. after following the exact steps you just described, It still isn't being killed
It does however, Blank the minecraftServer variable, preventing further use.

I tested this on ubuntu 16.04 with node 7.2.0

**Comment by Egoscio-zz** [comment]
At the moment, the `.stop()` function is merely doing this:

```js
  stop () {
    if (typeof this.minecraftServer.kill === 'function') {
      this.minecraftServer.kill()
    }
    this.minecraftServer = {}
    this.emit('stop')
  }
```

I could first make it run the `stop` command through the minecraft console and report back or continue with `stdin.pause()` and `.kill()`.

**Comment by KaidenP** [comment]
Well Either or would be fine, but rn `this.minecraftServer.kill()` doesn't seem to work, as the server still runs afterwards
